version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: ./php
        # image: php:7.0.33-fpm
        container_name: php-fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
    redis:
        image: redis:latest
        container_name: app_redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis.conf  
        command: redis-server /usr/local/etc/redis.conf    
        networks:
            - code-network 
    mysql:
        image: mysql:8.0.30
        command: mysqld --default-authentication-plugin=mysql_native_password
        container_name: app_mysql
        environment:
            - MYSQL_DATABASE=dev_sass
            - MYSQL_USER=magento
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3308:3306"
        volumes:
            - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
        networks:
            - code-network    


networks:
    code-network:
        driver: bridge
